# This workflow will build a Java project with Maven
name: Java CI with Maven

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "charts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        # https://github.com/actions/setup-java#usage
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "maven"

      - name: Run the tests in Maven
        run: mvn --batch-mode --no-transfer-progress --update-snapshots verify
