# This workflow will build a Java project with Maven
name: Java CI with Maven

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "charts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "maven"
      - run: mvn --batch-mode --no-transfer-progress --update-snapshots verify
